#! /bin/bash

sudo chown -R $(whoami) ~/.npm

if mv node_modules/zurb-foundation-5/scss styles/vendor/foundation; then
  rm -rf node_modules/zurb-foundation-5
fi

if mv node_modules/utility-belt/scss styles/vendor/utility-belt; then
  rm -rf node_modules/utility-belt
fi

if mv node_modules/slick-carousel/slick styles/vendor/slick; then
  rm -rf node_modules/slick-carousel
fi

npm run link-global
